{
 "title": "Zeebe Medic Load Tests",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Typical Load Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall FNI  per s",
   "type": "stat",
   "description": "Flow node instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?medic.*typical\",type!=\"PROCESS\", action!=\"activated\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed processes per s",
   "type": "stat",
   "description": "Process instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?medic.*typical\", action=\"completed\", type=\"PROCESS\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed tasks per s",
   "type": "stat",
   "description": "Tasks completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?medic.*typical\", action=\"completed\", type=\"SERVICE_TASK\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Mixed Load Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Overall FNI  per s",
   "type": "stat",
   "description": "Flow node instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"((c8-)?medic.*(mixed|realistic)|(c8-)?release-rolling)\", type!=\"PROCESS\", action!=\"activated\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed processes per s",
   "type": "stat",
   "description": "Process instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"((c8-)?medic.*(mixed|realistic)|(c8-)?release-rolling)\", action=\"completed\", type=\"PROCESS\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed tasks per s",
   "type": "stat",
   "description": "Tasks completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"((c8-)?medic.*(mixed|realistic)|(c8-)?release-rolling)\", action=\"completed\", type=\"SERVICE_TASK\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Daily Max Load Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Overall FNI  per s",
   "type": "stat",
   "description": "Flow node instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?medic-daily.*\", type!=\"PROCESS\", action!=\"activated\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed processes per s",
   "type": "stat",
   "description": "Process instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?medic-daily.*\",action=\"completed\", type=\"PROCESS\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed tasks per s",
   "type": "stat",
   "description": "Tasks completed or terminated per second over all partitions.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?medic-daily.*\", action=\"completed\", type=\"SERVICE_TASK\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Latency Load Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "1 - kube_pod_container_status_ready{container!~\"curator|curl\", namespace=~\".*-latency\"}",
     "legendFormat": "{{pod}} restart"
    }
   ]
  },
  {
   "title": "p50 Latency",
   "type": "stat",
   "description": "Average process instance execution latency",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?medic.*-typical|(c8-)?medic.*-latency\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?medic.*-typical|(c8-)?medic.*-latency\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Normal Benchmark p90",
   "type": "stat",
   "description": "90th percentile process instance execution latency",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?medic.*-typical\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?medic.*-typical\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Normal benchmark p99",
   "type": "stat",
   "description": "99th percentile process instance execution latency",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?medic.*-typical\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?medic.*-typical\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Latency Benchmark p90",
   "type": "stat",
   "description": "90th percentile process instance execution latency",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?medic.*-latency\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?medic.*-latency\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Latency benchmark p99 Latency",
   "type": "stat",
   "description": "99th percentile process instance execution latency",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?medic.*-latency\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?medic.*-latency\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Process Instance Execution Time (avg)",
   "type": "timeseries",
   "description": "Shows the execution time of a process instance. This means the time (latency) between creating the instance and completing it.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?medic.*latency\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "p50 {{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?medic.*latency\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "p99 {{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?medic.*latency\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "p50 {{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?medic.*latency\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "p99 {{namespace}}"
    }
   ]
  },
  { "title": "Medic Load Tests Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Health",
   "type": "table",
   "description": "Shows health per partition and pod",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "zeebe_health{namespace=~\"(c8-)?medic.*\"} ",
     "legendFormat": "Partition {{pod}} {{partition}}"
    },
    {
     "expr": "atomix_role{namespace=~\"(c8-)?medic.*\"} "
    }
   ]
  },
  {
   "title": "Pod Last Terminated Reason",
   "type": "table",
   "description": "Shows the reason for the last pod restart",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 44 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=~\"(c8-)?medic.*\", container=~\"zeebe|camunda\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Namespace max disk usage",
   "type": "stat",
   "description": "Shows how much disk is used at max by a broker per namespace",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{namespace=~\"(c8-)?medic.*\", persistentvolumeclaim=~\".*zeebe.*|.*camunda.*\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"(c8-)?medic.*\", persistentvolumeclaim=~\".*zeebe.*|.*camunda.*\"}) by (namespace)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Release Load Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Overall FNI  per s",
   "type": "stat",
   "description": "Flow node instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?release-8.*\",type!=\"PROCESS\", action!=\"activated\"}[$__range])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed processes per s",
   "type": "stat",
   "description": "Process instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?release-8.*\", action=\"completed\", type=\"PROCESS\"}[$__range])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed tasks per s",
   "type": "stat",
   "description": "Tasks completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?release-8.*\",action=\"completed\", type=\"SERVICE_TASK\"}[$__range])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "p50 Latency",
   "type": "stat",
   "description": "Average process instance execution latency",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?release-8.*\"}[$__range])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?release-8.*\"}[$__range])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "p90 Latency",
   "type": "stat",
   "description": "90th percentile process instance execution latency",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?release-8.*\"}[$__range])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?release-8.*\"}[$__range])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "stat",
   "description": "99th percentile process instance execution latency",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?release-8.*\"}[$__range])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?release-8.*\"}[$__range])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "table",
   "description": "Shows health per partition and pod",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "zeebe_health{namespace=~\"(c8-)?release.*\"} ",
     "legendFormat": "Partition {{pod}} {{partition}}"
    },
    {
     "expr": "atomix_role{namespace=~\"(c8-)?release.*\"} "
    }
   ]
  },
  {
   "title": "Namespace disk usage (max)",
   "type": "stat",
   "description": "Shows how much disk at max is used by brokers per namespace",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{namespace=~\"(c8-)?release.*\", persistentvolumeclaim=~\".*zeebe.*|.*camunda.*\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"(c8-)?release.*\", persistentvolumeclaim=~\".*zeebe.*|.*camunda.*\"}) by (namespace)",
     "legendFormat": "{{persistentvolumeclaim}} {{namespace}}"
    }
   ]
  }
 ]
}